
spring:
  application:
    name: gateway-server
  profiles:
    active: dev        # this selects registry-server-dev.yml from Config Server
  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL
      username: admin      # Config Server username
      password: admin   # Config Server password
      fail-fast: true
