server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: organization-service
          uri: http://localhost:9102
          predicates:
            - Path=/organizations/**
          filters:
            - RewritePath=/organizations/(?<segment>.*), /${segment}
